CREATE TABLE Patient (
                       id bigint GENERATED BY DEFAULT AS IDENTITY(START WITH 1) PRIMARY KEY NOT NULL,
                       Name varchar(255) NOT NULL ,
                       Surname varchar(255) NOT NULL ,
                       Patronymic varchar(255) NOT NULL ,
                       Phone varchar(255) NOT NULL
);

CREATE TABLE Doctor (
                      id bigint GENERATED BY DEFAULT AS IDENTITY(START WITH 1) PRIMARY KEY NOT NULL ,
                      Name varchar(255) NOT NULL ,
                      Surname varchar(255) NOT NULL ,
                      Patronymic varchar(255) NOT NULL ,
                      Specialization varchar(255) NOT NULL
);

CREATE TABLE Recipe (
                      id bigint GENERATED BY DEFAULT AS IDENTITY(START WITH 1) PRIMARY KEY NOT NULL ,
                      Description varchar(255),
                      Patient_id bigint NOT NULL ,
                      Doctor_id bigint NOT NULL ,
                      Date_creation date NOT NULL ,
                      Validity date NOT NULL ,
                      Priority_id bigint NOT NULL
);

CREATE TABLE Priority (
                        id bigint PRIMARY KEY NOT NULL ,
                        Name varchar(255) NOT NULL
);

alter table RECIPE
	add constraint RECIPE_PATIENT_ID_FK
		foreign key (PATIENT_ID) references PATIENT;

alter table RECIPE
	add constraint RECIPE_DOCTOR_ID_FK
		foreign key (DOCTOR_ID) references DOCTOR;

alter table RECIPE
	add constraint RECIPE_PRIORITY_ID_FK
		foreign key (PRIORITY_ID) references PRIORITY;
